#!/usr/bin/env python3
# Copyright (c) 2024 Arista Networks, Inc.  All rights reserved.

"""
"v3localize": accepts the passphrase, the auth type, the engineID, and
optionally the privacy type, and creates a localized hex string
that can be configured directly on the switch.
"""

import hashlib
import re

def _hasher( authType ):
   if authType == 'md5':
      hasher = hashlib.md5           # pylint: disable-msg=E1101
   elif authType == 'sha':
      hasher = hashlib.sha1          # pylint: disable-msg=E1101
   elif authType == 'sha224':
      hasher = hashlib.sha224        # pylint: disable-msg=E1101
   elif authType == 'sha256':
      hasher = hashlib.sha256        # pylint: disable-msg=E1101
   elif authType == 'sha384':
      hasher = hashlib.sha384        # pylint: disable-msg=E1101
   elif authType == 'sha512':
      hasher = hashlib.sha512        # pylint: disable-msg=E1101
   else:
      hasher = None
   return hasher

def keyFromPassphrase( phrase, authType ):
   """Generates a key from a passphrase as describe in RFC 2574 section A.2.
   authType should be 'md5', 'sha', or 'sha(224|256|384|512)'."""
   if isinstance( phrase, str ):
      phrase = phrase.encode()
   hasher = _hasher( authType )
   hash = hasher()            # pylint: disable-msg=W0622
   bytesLeft = 1048576
   concat = phrase
   while len( concat ) < 64:
      concat += phrase
   concatLen = len( concat )
   while bytesLeft > concatLen:
      hash.update( concat )
      bytesLeft -= concatLen
   if bytesLeft > 0:
      hash.update( concat[ 0 : bytesLeft ] )
   ku = hash.hexdigest()
   return ku

def localizePassphrase( phrase, authType, engineId, privType=None ):
   """Performs a key localization as described in RFC 2574 section 2.6.
   phrase is the plain ASCII passphrase.
   authType should be 'md5', 'sha', or 'sha(224|256|384|512)'.
   engineId is the *binary* value of the engineID.  (Not
   "8000757105..." but "\x80\x00\x75\x71\x05...")
   privType specifies the privacy protocol, like 'des', 'aes',
   'aes192' or 'aes256'.  This is needed when we need to create
   a longer kul for a stronger privacy protocol."""
   ku = bytes.fromhex( keyFromPassphrase( phrase, authType ) )
   hasher = _hasher( authType )
   localHash = hasher()
   localHash.update( ku + engineId + ku )
   kul = localHash.hexdigest()
   if privType is not None:
      bitsRequired = {
            'des': 128,
            'aes': 128,
            'aes192': 192,
            'aes256': 256,
            }[ privType.lower() ]
      # From draft-blumenthal-aes-usm-04 section 3.1.2.1
      while len( kul ) * 4 < bitsRequired:
         localHash = hasher()
         localHash.update( bytes.fromhex( kul ) )
         kul = kul + localHash.hexdigest()
      # Truncate in case we have too much.
      kul = kul[ : bitsRequired // 4 ]
   return kul

def main( args ):
   import argparse
   parser = argparse.ArgumentParser()
   parser.add_argument( "passphrase", help="The authentication or privacy passphrase to be localized" )
   parser.add_argument( "authType", help="The authentication protocol (e.g., aes, aes256)" )
   parser.add_argument( "engineId", help="The engineID to which to localize the passphrase" )
   parser.add_argument( "privType", nargs="?", default=None, help="The privacy algorithm in use.  Required when localizing a privacy passphrase when using aes192 or aes256." )
   args = parser.parse_args()
   assert args.authType in ( 'md5', 'sha', 'sha224', 'sha256', 'sha384', 'sha512' )
   assert args.privType in ( None, 'des', 'aes', 'aes192', 'aes256' )
   print( localizePassphrase( args.passphrase, args.authType, bytes.fromhex( args.engineId ), args.privType ) )

if __name__ == "__main__":
   import sys
   main( sys.argv[ 1: ] )
